# Generated by Django 4.0.4 on 2023-01-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_pokemon_created_at_alter_pokemon_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name_jp',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
