# Generated by Django 4.1.5 on 2023-01-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_alter_pokemon_name_ar_alter_pokemon_name_jp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
